//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC_ACE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int Id { get; set; }
        public int Prontuario { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string Logradouro { get; set; }
        public string NumeroLogradouro { get; set; }
        public string Bairro { get; set; }
        public int TelefoneResidencia { get; set; }
        public int TelefoneCelular { get; set; }
        public Nullable<int> TelefoneComercial { get; set; }
        public Nullable<int> EstadoCivil { get; set; }
        public Nullable<int> Escolaridade { get; set; }
        public string Profissao { get; set; }
        public Nullable<bool> Sexo { get; set; }
        public Nullable<int> Altura { get; set; }
        public Nullable<int> Peso { get; set; }
        public string Email { get; set; }
        public Nullable<bool> PacientePrecisaResponsavel { get; set; }
        public string NomeResponsavel { get; set; }
        public string NomeMae { get; set; }
        public string NomePai { get; set; }
        public string VinculoPrevidenciario { get; set; }
        public string Procedencia { get; set; }
    }
}
