//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC_ACE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoRecurso
    {
        public TipoRecurso()
        {
            this.Recurso = new HashSet<Recurso>();
        }
    
        public int codigo { get; set; }
        public string descricao { get; set; }
        public int ordem { get; set; }
    
        public virtual ICollection<Recurso> Recurso { get; set; }
    }
}
